---
- name: Create a group
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

# This task is not an idempotent,
# because the password_hash function will input a different Salt each time
# then generate a different hash value each time.
- name: Create a user
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"
    password: "{{ password | password_hash('sha512') }}"
    state: present
  changed_when: false

- name: Create a bin dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0700
  with_items:
    - /home/{{ user }}/.local/bin

- name: Copy bin files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/.local/bin/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
    - direnv
    - starship

- name: Update a bashrc
  ansible.builtin.blockinfile:
    dest: /home/{{ user }}/.bashrc
    insertafter: EOF
    content: |
      . ~/.bashrc.local

- name: Copy a bashrc.local
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/.{{ item }}
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_items:
    - bashrc.local
