---
- name: Fail if OS version is not supported
  ansible.builtin.fail:
    msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }} is currently not supported"
  when:
    - ansible_facts['distribution'] != "Rocky" or ansible_facts['distribution_major_version'] != "8"

- name: Create a group
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

- name: Create a user
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"
    password: "{{ password | password_hash('sha512') }}"
    state: present
  changed_when: false

- name: Copy bin files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - direnv

- name: Update bashrc with a created user
  blockinfile:
    dest: /home/{{ user }}/.bashrc
    insertafter: EOF
    content: |
      . ~/.bashrc.local

- name: Copy bashrc files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/.{{ item }}
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_items:
    - bashrc.local
