---
- name: Check the user created exists and that user can execute a command
  ansible.builtin.command:
    cmd: id
  become: true
  become_user: "{{ user }}"
  register: _result
  changed_when: false

- name: Show the result of the excuted command
  ansible.builtin.debug:
    msg: "{{ _result.stdout }}"

- name: Check the user created exists and that user can execute a copied command
  ansible.builtin.command:
    cmd: "{{ item }}"
  become: true
  become_user: "{{ user }}"
  with_items:
    - /usr/local/bin/direnv version
    # - source ~/.bashrc && direnv version
  changed_when: false
