---
- name: Check the user created can execute commands
  ansible.builtin.command:
    cmd: "{{ item }}"
  become: true
  become_user: "{{ user }}"
  with_items:
    - /bin/bash -lc docker version
    - /bin/bash -lc docker-compose version
  changed_when: false
