---
- name: Set up Stackstorm testbench
  hosts: localhost
  become: true
  roles:
    - role: os
      tags: os

    - role: docker
      tags: docker

    - role: st2
      tags: st2

    # - role: git
    #   tags: git

    # - role: tmux
    #   tags: tmux

    # - role: zsh
    #   tags: zsh

    # - role: nvim
    #   tags: nvim

    # - role: vscode
    #   tags: vscode

    # - role: docker
    #   tags: docker

    # - role: python3
    #   tags: python3

    # - role: ansible
    #   tags: ansible
