---
- name: Install OS packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - python38
    - python38-pip

- name: Clone a git repo
  ansible.builtin.git:
    repo: "https://github.com/codequokka/st2-docker"
    dest: /home/{{ user }}/st2-docker
    version: customize
    depth: 1
  become: true
  become_user: "{{ user }}"
  tags:
    - skip_ansible_lint

- name: Create a pack.dev dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  with_items:
    - /home/{{ user }}/packs.dev

# - name: Start ST2 containers
#   ansible.builtin.command:
#     cmd: /usr/local/bin/docker-compose up -d
#     chdir: /home/{{ user }}/st2-docker
#   become: true
#   become_user: "{{ user }}"
#   changed_when: false

