---
- name: Install OS packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - python38
    - python38-pip

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.8
  with_items:
    - st2client

- name: Create symblic links
  ansible.builtin.file:
    src: /usr/local/bin/{{ item }}
    dest: /home/{{ user }}/.local/bin/{{ item }}
  with_items:
    - st2

- name: Clone a git repo
  ansible.builtin.git:
    repo: "{{ st2_docker_repo }}"
    dest: /home/{{ user }}/st2/st2-docker
    version: customize
    depth: 1
  become: true
  become_user: "{{ user }}"
  tags:
    - skip_ansible_lint

- name: Create a pack.dev dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
    recurse: true
  with_items:
    - /home/{{ user }}/st2/packs.dev

# - name: Start ST2 containers
#   ansible.builtin.command:
#     cmd: /bin/bash -lc docker-compose up -d
#     chdir: /home/{{ user }}/st2/st2-docker
#   become: true
#   become_user: "{{ user }}"
#   changed_when: false

